window.lang = {
	"en": {
		"title": 		"Who's That Pokémon?",
		"dontknow": 	"I don't know!",
		"generation": 	"Generation",
		"generation-all": "All",
		"generation-1": "Gen 1",
		"generation-2": "Gen 2",
		"generation-3": "Gen 3",
		"generation-4": "Gen 4",
		"generation-5": "Gen 5",
		"generation-6": "Gen 6",
		"generation-7": "Gen 7",
		"generation-8": "Gen 8",
		"difficulty":	"Difficulty",
		"difficulty-0":	"Normal",
		"difficulty-1":	"Ultra",
		"difficulty-2":	"Master",
		"difficulty-3":	"Elite",
		"difficulty-4":	"Easy",
		"spelling":		"Spelling",
		"spelling-exact":"Exact",
		"spelling-forgiving": "Forgiving",
		"sound":		"Sound",
		"on":			"On",
		"off":			"Off",
		"streak":		"Streak",
		"time":			"Time",
		"best":			"Best",
		"current":		"Current",
		"previous":		"Previous",
		"average":		"Average",
		"alsoknownas": 	"Also Known As",
		"nextpokemon":	"Next Pokémon in _TIME_ seconds",
		"loadfail":		'This is taking a while to load. Do you want to try loading another one? It won\'t affect your streak. <a href="#" onclick="newPokemon();">Load a new Pokémon?</a>',
		"slowconn":		"Is your connection slow or down? Maybe try a harder difficulty, they load faster.",
		"loadnew":		"Load a new Pokémon?",
		"streak-info":	"Your streaks and times are separate for each difficulty",
		"settings-effect": "Your new settings will take effect for the next Pokémon",
		"infobox":		'New: Gen 8 added! Sword and Shield do not have sprites, so Ultra and Master modes do not work for this generation. If you find any issues, let me know on GitHub!',
		"footer":  		'Send feedback or contribute at <a href="https://github.com/menardi/whosthatpokemon" title="Who\'s That Pokémon on Github">GitHub</a>.<br />All images &copy; Nintendo. Gen 1-5 artwork, sprites and data from <a href="http://veekun.com/dex/downloads" title="Veekun Downloads Page">Veekun</a>. Others from <a href="http://bulbapedia.bulbagarden.net">Bulbapedia</a>. Sounds from <a href="https://github.com/sora10pls">sora10pls</a>.',
		"language":		'Language',
		"settings":		'Settings',
		"stats":		'Stats',
	},
	"fr": {
		"title": 		"Quel est ce Pokémon?",
		"dontknow": 	"Je ne sais pas!",
		"generation": 	"Génération",
		"generation-all": "Tous",
		"generation-1": "Gén 1",
		"generation-2": "Gén 2",
		"generation-3": "Gén 3",
		"generation-4": "Gén 4",
		"generation-5": "Gén 5",
		"generation-6": "Gén 6",
		"generation-7": "Gén 7",
		"generation-8": "Gén 8",
		"difficulty":	"Difficulté",
		"difficulty-0":	"Normale",
		"difficulty-1":	"Hyper",
		"difficulty-2":	"Master",
		"difficulty-3":	"Élite",
		"difficulty-4":	"Facile",
		"spelling":		"Orthographe",
		"spelling-exact":"Exacte",
		"spelling-forgiving": "Tolérant",
		"sound":		"Son",
		"on":			"Oui",
		"off":			"Non",
		"streak":		"Consécutif",
		"time":			"Chronom&egrave;tre",
		"best":			"Meilleur",
		"current":		"Actuel",
		"previous":		"Précédent",
		"average":		"Moyenne",
		"alsoknownas": 	"Aussi connu sous le nom de",
		"nextpokemon":	"Pokémon suivante dans _TIME_ secondes",
		"loadfail":		"C'est lent &agrave; charger. Essayez un autre?",
		"slowconn":		"Connexion lente?",
		"loadnew":		"Charger un nouveau Pokémon?",
		"streak-info":	"Vos records sont distincts pour chaque difficulté",
		"settings-effect": "Vos nouveaux paramètres prendront effet pour la prochaine Pokémon",
		"infobox":		'New: Gen 8 added! Sword and Shield do not have sprites, so Ultra and Master modes do not work for this generation. If you find any issues, let me know on GitHub!',
		"footer":		'Toutes les images de Nintendo. Les images et les données pour gén 1-5 de <a href="http://veekun.com/dex/downloads">Veekun</a>. Les autres de <a href="http://bulbapedia.bulbagarden.net">Bulbapedia</a>. Cri de <a href="https://github.com/sora10pls">sora10pls</a>. Contribuez à <a href="https://github.com/Menardi/whosthatpokemon" title="Who\'s That Pokémon à Github">Github</a>.',
		"language":		'Langue',
		"settings":		'Options',
		"stats":		'Stats',
	},
	"de": {
		"title": 		"Wer ist das Pokémon?",
		"dontknow": 	"Ich wei&szlig; nicht",
		"generation": 	"Generation",
		"generation-all": "Alle",
		"generation-1": "Gen 1",
		"generation-2": "Gen 2",
		"generation-3": "Gen 3",
		"generation-4": "Gen 4",
		"generation-5": "Gen 5",
		"generation-6": "Gen 6",
		"generation-7": "Gen 7",
		"generation-8": "Gen 8",
		"difficulty":	"Schwierigkeit",
		"difficulty-0":	"Normale",
		"difficulty-1":	"Hyper",
		"difficulty-2":	"Meister",
		"difficulty-3":	"Elite",
		"difficulty-4":	"Einfach",
		"spelling":		"Rechtschreibung",
		"spelling-exact":"Exakt",
		"spelling-forgiving": "Tolerant",
		"sound":		"Ton",
		"on":			"Ja",
		"off":			"Nein",
		"streak":		"Konsekutiv",
		"time":			"Zeit",
		"best":			"Beste",
		"current":		"Gegenw&auml;rtig",
		"previous":		"Fr&uuml;her",
		"average":		"Durchschnitt",
		"alsoknownas": 	"Also Known As",
		"nextpokemon":	"Weiter Pokémon in _TIME_ Sekunden",
		"loadfail":		"Dies ist nur langsam geladen. Versuchen Sie ein anderes?",
		"slowconn":		"Langsame Verbindung?",
		"loadnew":		"Legen Sie eine neue Pokémon?",
		"streak-info":	"Ihre Aufzeichnungen sind für jeden Schwierigkeitsgrad separaten",
		"settings-effect": "Ihre neuen Einstellungen werden für die nächste Pokémon nehmen",
		"infobox":		'New: Gen 8 added! Sword and Shield do not have sprites, so Ultra and Master modes do not work for this generation. If you find any issues, let me know on GitHub!',
		"footer":		'Alle Bilder Nintendo. Bilder und Daten von <a href="http://veekun.com/dex/downloads">Veekun</a> und <a href="http://bulbapedia.bulbagarden.net">Bulbapedia</a>. Ruf von <a href="https://github.com/sora10pls">sora10pls</a>. Beitragen bei <a href="https://github.com/Menardi/whosthatpokemon" title="Who\'s That Pokémon à Github">Github</a>.',
		"language":		'Sprache',
		"settings":		'Options',
		"stats":		'Statistik',
	},
	"ja": {
		"title": 		"だれだ？",
		"dontknow": 	"わかりません",
		"generation": 	"世代",
		"generation-all": "すべて",
		"generation-1": "第1世代",
		"generation-2": "第2世代",
		"generation-3": "第3世代",
		"generation-4": "第4世代",
		"generation-5": "第5世代",
		"generation-6": "第6世代",
		"generation-7": "第7世代",
		"generation-8": "第8世代",
		"difficulty":	"難度",
		"difficulty-0":	"普通",
		"difficulty-1":	"ハイパー",
		"difficulty-2":	"マスター",
		"difficulty-3":	"天王",
		"difficulty-4":	"簡単",
		"spelling":		"スペリング",
		"spelling-exact":"正確",
		"spelling-forgiving": "甘い",
		"sound":		"サウンド",
		"on":			"オン",
		"off":			"オフ",
		"streak":		"連勝",
		"time":			"時間",
		"best":			"自己ベスト",
		"current":		"現在",
		"previous":		"前回",
		"average":		"平均",
		"alsoknownas": 	"他の言語での名前",
		"nextpokemon":	"_TIME_秒で次のポケモンが登場します",
		"loadfail":		'通信エラーが発生したため、新しいポケモンをロードするために、<a href="#" onclick="newPokemon();">ここにクリックしてください。</a>連勝が影響を受けません。',
		"slowconn":		"接続が遅い可能性があります。ロード時間を改善するために、他の難度をご選択ください。",
		"loadnew":		"新たなポケモンをロードしますか？",
		"streak-info":	"各難度で連勝や時間が違います。",
		"settings-effect": "この後で新しい設定が有効になります。",
		"infobox":		'New: Gen 8 added! Sword and Shield do not have sprites, so Ultra and Master modes do not work for this generation. If you find any issues, let me know on GitHub!',
		"footer":  		'すべての画像 &copy; Nintendo. イラスト、スプライト、データが<a href="http://veekun.com/dex/downloads" title="Veekun Downloads Page">Veekun</a>、<a href="http://bulbapedia.bulbagarden.net">Bulbapedia</a>、<a href="https://github.com/sora10pls">sora10pls</a>。から取られました。フィードバック：<a href="https://github.com/Menardi/whosthatpokemon">GitHub</a>。',
		"language":		'ランゲージ',
		"settings":		'オプション',
		"stats":		'レコード',
	}
};