lang = {
	"en": {
		"title": 		"Who's That Pokemon?",
		"dontknow": 	"I don't know!",
		"generation": 	"Generation",
		"generation-all": "All",
		"generation-1": "Gen 1",
		"generation-2": "Gen 2",
		"generation-3": "Gen 3",
		"generation-4": "Gen 4",
		"generation-5": "Gen 5",
		"difficulty":	"Difficulty",
		"difficulty-0":	"Normal",
		"difficulty-1":	"Ultra",
		"difficulty-2":	"Master",
		"difficulty-3":	"Elite",
		"spelling":		"Spelling",
		"spelling-exact":"Exact",
		"spelling-forgiving": "Forgiving",
		"sound":		"Sound",
		"on":			"On",
		"off":			"Off",
		"streak":		"Streak",
		"time":			"Time",
		"best":			"Best",
		"current":		"Current",
		"previous":		"Previous",
		"average":		"Average",
		"alsoknownas": 	"Also Known As",
		"nextpokemon":	"Next Pok&eacute;mon in _TIME_ seconds",
		"loadfail":		'This is taking a while to load. Do you want to try loading another one? It won\'t affect your streak. <a href="#" onclick="newPokemon();">Load a new Pok&eacute;mon?</a>',
		"slowconn":		"Is your connection slow or down? Maybe try a harder difficulty, they load faster.",
		"loadnew":		"Load a new Pok&eacute;mon?",
		"streak-info":	"Your streaks and times are separate for each difficulty",
		"settings-effect": "Your new settings will take effect for the next Pok&eacute;mon",
		"infobox":		'Visit Who\'s That Pokémon on your mobile and check out the new mobile-friendly version!',
		"footer":  		'All images &copy; Nintendo. Artwork, sprites and data from <a href="http://veekun.com/dex/downloads" title="Veekun Downloads Page">Veekun</a>. Site made by <a href="http://blog.gearoid.me">Gear&oacute;id Moroney',
		"language":		'Language',
		"settings":		'Settings',
		"stats":		'Stats',
	},
	"fr": {
		"title": 		"Quel Pok&eacute;mon Est-Ce?",
		"dontknow": 	"Je ne sais pas!",
		"generation": 	"G&eacute;n&eacute;ration",
		"generation-all": "Tous",
		"generation-1": "G&eacute;n 1",
		"generation-2": "G&eacute;n 2",
		"generation-3": "G&eacute;n 3",
		"generation-4": "G&eacute;n 4",
		"generation-5": "G&eacute;n 5",
		"difficulty":	"Difficult&eacute;",
		"difficulty-0":	"Normale",
		"difficulty-1":	"Hyper",
		"difficulty-2":	"Master",
		"difficulty-3":	"&Eacute;lite",
		"spelling":		"Orthographe",
		"spelling-exact":"Exact",
		"spelling-forgiving": "Tol&eacute;rant",
		"sound":		"Sonore",
		"on":			"Oui",
		"off":			"Non",
		"streak":		"Cons&eacute;tif",
		"time":			"Chronom&egrave;tre",
		"best":			"Meilleur",
		"current":		"Actuel",
		"previous":		"Pr&eacute;c&eacute;edent",
		"average":		"Moyenne",
		"alsoknownas": 	"Also Known As",
		"nextpokemon":	"Pok&eacute;mon suivante en _TIME_ secondes",
		"loadfail":		"C'est lent &agrave; charger. Essayez un autre?",
		"slowconn":		"Connexion lente?",
		"loadnew":		"Charger un nouveau Pok&eacute;mon?",
		"streak-info":	"Vos records sont distincts pour chaque difficulté",
		"settings-effect": "Vos nouveaux paramètres prendront effet pour la prochaine Pok&eacute;mon",
		"infobox":		'Visite "Quel Pok&eacute;mon Est-Ce?" sur votre mobile et d\'essayer la nouvelle version pour les petits écrans!',
		"footer":		'Toutes les images de Nintendo. Les images et les données de <a href="http://veekun.com/dex/downloads">Veekun</a>. Créé par <a href="http://gearoid.me">Gear&oacute;id Moroney</a>.',
		"language":		'Langue',
		"settings":		'Options',
		"stats":		'Stats',
	},
	"de": {
		"title": 		"Wer ist das Pokémon?",
		"dontknow": 	"Ich wei&szlig; nicht",
		"generation": 	"Generation",
		"generation-all": "Alle",
		"generation-1": "Gen 1",
		"generation-2": "Gen 2",
		"generation-3": "Gen 3",
		"generation-4": "Gen 4",
		"generation-5": "Gen 5",
		"difficulty":	"Schwierigkeit",
		"difficulty-0":	"Normale",
		"difficulty-1":	"Hyper",
		"difficulty-2":	"Meister",
		"difficulty-3":	"Elite",
		"spelling":		"Rechtschreibung",
		"spelling-exact":"Exakt",
		"spelling-forgiving": "Tolerant",
		"sound":		"Ton",
		"on":			"Ja",
		"off":			"Nein",
		"streak":		"Konsekutiv",
		"time":			"Zeit",
		"best":			"Beste",
		"current":		"Gegenw&auml;rtig",
		"previous":		"Fr&uuml;her",
		"average":		"Durchschnitt",
		"alsoknownas": 	"Also Known As",
		"nextpokemon":	"Weiter Pok&eacute;mon in _TIME_ Sekunden",
		"loadfail":		"Dies ist nur langsam geladen. Versuchen Sie ein anderes?",
		"slowconn":		"Langsame Verbindung?",
		"loadnew":		"Legen Sie eine neue Pok&eacute;mon?",
		"streak-info":	"Ihre Aufzeichnungen sind für jeden Schwierigkeitsgrad separaten",
		"settings-effect": "Ihre neuen Einstellungen werden für die nächste Pok&eacute;mon nehmen",
		"infobox":		'Visit Who\'s That Pokémon on your mobile and check out the new mobile-friendly version!',
		"footer":		'Alle Bilder Nintendo. Bilder und Daten von <a href="http://veekun.com/dex/downloads">Veekun</a>. Erstellt von <a href="http://gearoid.me">Gear&oacute;id Moroney</a>.',
		"language":		'Sprache',
		"settings":		'Options',
		"stats":		'Statistik',
	},
	"jp": {
		"title": 		"だれだ？",
		"dontknow": 	"わかりません",
		"generation": 	"世代",
		"generation-all": "すべて",
		"generation-1": "第1世代",
		"generation-2": "第2世代",
		"generation-3": "第3世代",
		"generation-4": "第4世代",
		"generation-5": "第5世代",
		"difficulty":	"難度",
		"difficulty-0":	"普通",
		"difficulty-1":	"ハイパー",
		"difficulty-2":	"マスター",
		"difficulty-3":	"天王",
		"spelling":		"スペリング",
		"spelling-exact":"正確",
		"spelling-forgiving": "甘い",
		"sound":		"サウンド",
		"on":			"オン",
		"off":			"オフ",
		"streak":		"連勝",
		"time":			"時間",
		"best":			"自己ベスト",
		"current":		"現在",
		"previous":		"前回",
		"average":		"平均",
		"alsoknownas": 	"他の言語での名前",
		"nextpokemon":	"_TIME_秒で次のポケモンが登場します",
		"loadfail":		'通信エラーが発生したため、新しいポケモンをロードするために、<a href="#" onclick="newPokemon();">ここにクリックしてください。</a>連勝が影響を受けません。',
		"slowconn":		"接続が遅い可能性があります。ロード時間を改善するために、他の難度をご選択ください。",
		"loadnew":		"新たなポケモンをロードしますか？",
		"streak-info":	"各難度で連勝や時間が違います。",
		"settings-effect": "この後で新しい設定が有効になります。",
		"infobox":		'Visit Who\'s That Pokémon on your mobile and check out the new mobile-friendly version!',
		"footer":  		'すべての画像 &copy; Nintendo. イラスト、スプライト、データが<a href="http://veekun.com/dex/downloads" title="Veekun Downloads Page">Veekun</a>から取られました。<br/>サイト作成者：<a href="http://blog.gearoid.me">Gear&oacute;id Moroney',
		"language":		'ランゲージ',
		"settings":		'オプション',
		"stats":		'レコード',
	}
};