lang = {
	"en": {
		"title": 		"Who's That Pokemon?",
		"dontknow": 	"I don't know!",
		"generation": 	"Generation",
		"generation-1": "Gen 1",
		"generation-2": "Gen 2",
		"generation-3": "Gen 3",
		"generation-4": "Gen 4",
		"generation-5": "Gen 5",
		"difficulty":	"Difficulty",
		"difficulty-0":	"Normal",
		"difficulty-1":	"Ultra",
		"difficulty-2":	"Master",
		"difficulty-3":	"Elite",
		"spelling":		"Spelling",
		"spelling-exact":"Exact",
		"spelling-forgiving": "Forgiving",
		"sound":		"Sound",
		"on":			"On",
		"off":			"Off",
		"streak":		"Streak",
		"time":			"Time",
		"best":			"Best",
		"current":		"Current",
		"previous":		"Previous",
		"average":		"Average",
		"nextpokemon":	"Next Pok&eacute;mon in _TIME_ seconds",
		"loadfail":		"This is taking a while to load. Do you want to try loading another one? It won't affect your streak.",
		"slowconn":		"Is your connection slow or down? Maybe try a harder difficulty, they load faster.",
		"loadnew":		"Load a new Pok&eacute;mon?",
		"streak-info":	"Your streaks and times are separate for each difficulty",
		"settings-effect": "Your new settings will take effect for the next Pok&eacute;mon",
		"infobox":		'"Who\'s That Pokémon?" has been translated to French and German! This has been mostly automated, so if you can help make it better, please <a href="mailto:hello@gearoid.me">email me</a> or contribute on <a href="https://github.com/Menardi/whosthatpokemon">GitHub</a>. New languages welcome!'
	},
	"fr": {
		"title": 		"Quel Pok&eacute;mon Est-Ce?",
		"dontknow": 	"Je ne sais pas!",
		"generation": 	"G&eacute;n&eacute;ration",
		"generation-1": "G&eacute;n 1",
		"generation-2": "G&eacute;n 2",
		"generation-3": "G&eacute;n 3",
		"generation-4": "G&eacute;n 4",
		"generation-5": "G&eacute;n 5",
		"difficulty":	"Difficult&eacute;",
		"difficulty-0":	"Normale",
		"difficulty-1":	"Hyper",
		"difficulty-2":	"Master",
		"difficulty-3":	"&Eacute;lite",
		"spelling":		"Orthographe",
		"spelling-exact":"Exact",
		"spelling-forgiving": "Tol&eacute;rant",
		"sound":		"Sonore",
		"on":			"Oui",
		"off":			"Non",
		"streak":		"Cons&eacute;tif",
		"time":			"Chronom&egrave;tre",
		"best":			"Meilleur",
		"current":		"Actuel",
		"previous":		"Pr&eacute;c&eacute;edent",
		"average":		"Moyenne",
		"nextpokemon":	"Pok&eacute;mon suivante en _TIME_ secondes",
		"loadfail":		"C'est lent &agrave; charger. Essayez un autre?",
		"slowconn":		"Connexion lente?",
		"loadnew":		"Charger un nouveau Pok&eacute;mon?",
		"streak-info":	"Vos records sont distincts pour chaque difficulté",
		"settings-effect": "Vos nouveaux paramètres prendront effet pour la prochaine Pok&eacute;mon",
		"infobox":		'"Quel Pokémon Est-Ce?" a été traduit en français et en allemand! Cela a été principalement automatisé, donc si vous pouvez aider à faire mieux, s\'il vous plaît <a href="mailto:hello@gearoid.me">écrivez-moi</a> ou contribuer sur <a href="https://github.com/Menardi/whosthatpokemon">GitHub</a>. Nouvelles langues bienvenus!',
		"footer":		'Toutes les images de Nintendo. Les images et les données de <a href="http://veekun.com/dex/downloads">Veekun</a>. Créé par <a href="http://gearoid.me">Gear&oacute;id Moroney</a>.'
	},
	"de": {
		"title": 		"Wer ist das Pokémon?",
		"dontknow": 	"Ich wei&szlig; nicht",
		"generation": 	"Generation",
		"generation-1": "Gen 1",
		"generation-2": "Gen 2",
		"generation-3": "Gen 3",
		"generation-4": "Gen 4",
		"generation-5": "Gen 5",
		"difficulty":	"Schwierigkeit",
		"difficulty-0":	"Normale",
		"difficulty-1":	"Hyper",
		"difficulty-2":	"Meister",
		"difficulty-3":	"Elite",
		"spelling":		"Rechtschreibung",
		"spelling-exact":"Exakt",
		"spelling-forgiving": "Tolerant",
		"sound":		"Ton",
		"on":			"Ja",
		"off":			"Nein",
		"streak":		"Konsekutiv",
		"time":			"Zeit",
		"best":			"Beste",
		"current":		"Gegenw&auml;rtig",
		"previous":		"Fr&uuml;her",
		"average":		"Durchschnitt",
		"nextpokemon":	"Weiter Pok&eacute;mon in _TIME_ Sekunden",
		"loadfail":		"Dies ist nur langsam geladen. Versuchen Sie ein anderes?",
		"slowconn":		"Langsame Verbindung?",
		"loadnew":		"Legen Sie eine neue Pok&eacute;mon?",
		"streak-info":	"Ihre Aufzeichnungen sind für jeden Schwierigkeitsgrad separaten",
		"settings-effect": "Ihre neuen Einstellungen werden für die nächste Pok&eacute;mon nehmen",
		"infobox":		'"Wer ist das Pokémon?" hat übersetzt Französisch und Deutsch! Dies war weitgehend automatisiert, so dass, wenn Sie helfen können es besser machen, bitte <a href="mailto:hello@gearoid.me">mailen Sie mir</a> oder tragen auf <a href="https://github.com/Menardi/whosthatpokemon">GitHub</a>. Neue Sprachen begrüßen zu dürfen!',
		"footer":		'Alle Bilder Nintendo. Bilder und Daten von <a href="http://veekun.com/dex/downloads">Veekun</a>. Erstellt von <a href="http://gearoid.me">Gear&oacute;id Moroney</a>.'
	},
};